---
- import_tasks: ansible-galaxy-requirements.yml
- block:
  - import_tasks: users.yml
  - import_tasks: mount-extra-volume.yml
  - import_tasks: install-docker.yml
  - import_tasks: harden-docker.yml
    tags:
    - molecule-notest
  become: true